/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Dialogues")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class Dialogues : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "c776e9477979854429b714b912816d8d";
        public override string ScriptGUID => s_scriptGUID;

        [Header("Managers")]
        [SerializeField] public UnityEngine.GameObject m_gameManagerGo = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_gameManagerGo),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
            };
        }
    }
}

#endif
