/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GameManager")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class GameManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1313d53594d9e0341b3838657871fa7e";
        public override string ScriptGUID => s_scriptGUID;

        [Header("Managers")]
        [SerializeField] public UnityEngine.GameObject m_uiManagerGo = default;
        [Header("Spawners")]
        [SerializeField] public UnityEngine.GameObject m_travelSpawner1 = default;
        [SerializeField] public UnityEngine.GameObject m_travelSpawner2 = default;
        [SerializeField] public UnityEngine.GameObject m_travelSpawner3 = default;
        [SerializeField] public UnityEngine.GameObject m_travelSpawner4 = default;
        [SerializeField] public UnityEngine.GameObject m_travelSpawner5 = default;
        [SerializeField] public UnityEngine.GameObject m_travelSpawner6 = default;
        [SerializeField] public UnityEngine.GameObject m_travelSpawner7 = default;
        [SerializeField] public UnityEngine.GameObject m_travelSpawner8 = default;
        [SerializeField] public UnityEngine.GameObject m_kpopSpawner = default;
        [SerializeField] public UnityEngine.GameObject m_catCoffeSpawner = default;
        [Header("Teleport Tap Handlers")]
        [SerializeField] public Highrise.Client.TapHandler m_travelTapH = default;
        [SerializeField] public Highrise.Client.TapHandler m_kpopTapH = default;
        [SerializeField] public Highrise.Client.TapHandler m_catCoffeTapH = default;
        [Header("Activate Quizz Tap Handlers")]
        [SerializeField] public Highrise.Client.TapHandler m_travelQuizTapH1 = default;
        [SerializeField] public Highrise.Client.TapHandler m_travelQuizTapH2 = default;
        [SerializeField] public Highrise.Client.TapHandler m_travelQuizTapH3 = default;
        [SerializeField] public Highrise.Client.TapHandler m_travelQuizTapH4 = default;
        [SerializeField] public Highrise.Client.TapHandler m_travelQuizTapH5 = default;
        [SerializeField] public Highrise.Client.TapHandler m_travelQuizTapH6 = default;
        [SerializeField] public Highrise.Client.TapHandler m_travelQuizTapH7 = default;
        [SerializeField] public Highrise.Client.TapHandler m_travelQuizTapH8 = default;
        [SerializeField] public Highrise.Client.TapHandler m_catQuizTapH1 = default;
        [SerializeField] public Highrise.Client.TapHandler m_catQuizTapH2 = default;
        [SerializeField] public Highrise.Client.TapHandler m_catQuizTapH3 = default;
        [SerializeField] public Highrise.Client.TapHandler m_catQuizTapH4 = default;
        [SerializeField] public Highrise.Client.TapHandler m_catQuizTapH5 = default;
        [SerializeField] public Highrise.Client.TapHandler m_catQuizTapH6 = default;
        [SerializeField] public Highrise.Client.TapHandler m_catQuizTapH7 = default;
        [SerializeField] public Highrise.Client.TapHandler m_catQuizTapH8 = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_uiManagerGo),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_travelSpawner1),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_travelSpawner2),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_travelSpawner3),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_travelSpawner4),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_travelSpawner5),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_travelSpawner6),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_travelSpawner7),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_travelSpawner8),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_kpopSpawner),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_catCoffeSpawner),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_travelTapH),
                CreateSerializedProperty(_script.GetPropertyAt(12), m_kpopTapH),
                CreateSerializedProperty(_script.GetPropertyAt(13), m_catCoffeTapH),
                CreateSerializedProperty(_script.GetPropertyAt(14), m_travelQuizTapH1),
                CreateSerializedProperty(_script.GetPropertyAt(15), m_travelQuizTapH2),
                CreateSerializedProperty(_script.GetPropertyAt(16), m_travelQuizTapH3),
                CreateSerializedProperty(_script.GetPropertyAt(17), m_travelQuizTapH4),
                CreateSerializedProperty(_script.GetPropertyAt(18), m_travelQuizTapH5),
                CreateSerializedProperty(_script.GetPropertyAt(19), m_travelQuizTapH6),
                CreateSerializedProperty(_script.GetPropertyAt(20), m_travelQuizTapH7),
                CreateSerializedProperty(_script.GetPropertyAt(21), m_travelQuizTapH8),
                CreateSerializedProperty(_script.GetPropertyAt(22), m_catQuizTapH1),
                CreateSerializedProperty(_script.GetPropertyAt(23), m_catQuizTapH2),
                CreateSerializedProperty(_script.GetPropertyAt(24), m_catQuizTapH3),
                CreateSerializedProperty(_script.GetPropertyAt(25), m_catQuizTapH4),
                CreateSerializedProperty(_script.GetPropertyAt(26), m_catQuizTapH5),
                CreateSerializedProperty(_script.GetPropertyAt(27), m_catQuizTapH6),
                CreateSerializedProperty(_script.GetPropertyAt(28), m_catQuizTapH7),
                CreateSerializedProperty(_script.GetPropertyAt(29), m_catQuizTapH8),
            };
        }
    }
}

#endif
