/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/LocalSounds")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class LocalSounds : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "5ff18d4a94ca10e4080fe4566c0d1386";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.AudioClip m__correctSound = default;
        [SerializeField] public UnityEngine.AudioClip m__incorrectSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m__correctSound),
                CreateSerializedProperty(_script.GetPropertyAt(1), m__incorrectSound),
            };
        }
    }
}

#endif
